[[file_copied]]
source = "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux64"
destination = "~/.local/bin/jq"

[[file_present]]
file = "~/.local/bin/jq"
permissions = "755"

[[package_present]]
install_command = """bash -c "$(curl -fsSL https://raw.githubusercontent.com/get-gah/gah/refs/heads/master/tools/install.sh)" """
uninstall_command = "rm ~/.local/bin/gah"
# hash will make sure no cached results are used
# command checks if the command exists
# true will make sure that the exit code is 0, even when the command does not exist
version_command = "hash -r 2>/dev/null; command -v gah >/dev/null && gah version; true"
version = "1.7.0"
type = "custom"
package = "gah"
