[[key_value_present]]
file = "~/.config/eget.toml"
key.global.target = "~/.local/bin"

[[package_present]]
type = "custom"
package = "eget"
install_command = "cd ~/.local/bin && curl https://zyedidia.github.io/eget.sh | sh"
uninstall_command = "rm ~/.local/bin/eget"
version_command = "eget --version"
version = "1.3.4"
