include = [
    "config:lazyvim/check-config.toml",
    "config:plugins/autosave.toml",
    "config:plugins/catppuccin.toml",
    "config:plugins/autotag.toml",
    "config:plugins/lsp.toml",
    "config:plugins/mini-icons.toml",
    "config:plugins/sql.toml",
    "config:plugins/whichkey.toml",
    "config:plugins/python.toml",
    "config:plugins/git.toml",
    "config:plugins/fidget.toml",
]

[[package_present]]
type = "rust"
package = "fd-find"
