include = [
  "config:lazyvim/check-config.toml",
  "config:autotag/check-config.toml",
  "config:plugins/autosave.toml",
  "config:plugins/catppuccin.toml",
  "config:python",
  # "config:plugins/git.toml",
  "config:plugins/fidget.toml",
]
