[[package_present]]
version = "0.66.1"
version_command = "hash -r 2>/dev/null; command -v fzf >/dev/null && fzf --version; true"
type = "custom"
package = "fzf"
install_command = "gah install junegunn/fzf --unattended"
uninstall_command = "rm ~/.local/bin/fzf"

[[file_copied]]
source = "config:20-fzf.sh"
destination_dir = "~/.bashrc.d"

[[file_copied]]
source = "config:20-fzf-rg.sh"
destination_dir = "~/.bashrc.d"
