[[package_present]]
version = "0.66.1"
version_command = "hash -r 2>/dev/null; command -v fzf >/dev/null && fzf --version; true"
type = "custom"
package = "fzf"
install_command = "gah install junegunn/fzf --unattended"
uninstall_command = "rm ~/.local/bin/fzf"
