[[file_copied]]
source = "config:90-cd-pre-hook-venv.sh"
destination = "~/.bashrc.d/90-cd-pre-hook-venv.sh"

[[package_present]]
type = "custom"
package = "uv"
install_command = "curl -LsSf https://astral.sh/uv/0.9.7/install.sh | sh"
uninstall_command = "rm ~/.local/bin/uv ~/.local/bin/uvx"
version_command = "uv --version"
version = "0.9.7"
